"""add_scattered_and_purchase_price

Revision ID: 03af525657e5
Revises: bbf28ffdb4c0
Create Date: 2026-03-26 14:13:39.419463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03af525657e5'
down_revision = 'bbf28ffdb4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drug_name'))

    op.drop_table('drug')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_name'))
        batch_op.drop_index(batch_op.f('ix_patient_student_id'))

    op.drop_table('patient')
    with op.batch_alter_table('diagnosis_dict', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_dict_code'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_dict_name'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_dict_pinyin'))

    op.drop_table('diagnosis_dict')
    op.drop_table('payment')
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_timestamp'))

    op.drop_table('visit')
    op.drop_table('prescription_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prescription_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('visit_id', sa.INTEGER(), nullable=True),
    sa.Column('drug_id', sa.INTEGER(), nullable=True),
    sa.Column('usage', sa.VARCHAR(length=100), nullable=True),
    sa.Column('dosage', sa.VARCHAR(length=50), nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=50), nullable=True),
    sa.Column('days', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('price_at_visit', sa.FLOAT(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('timing', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('chief_complaint', sa.TEXT(), nullable=True),
    sa.Column('present_illness', sa.TEXT(), nullable=True),
    sa.Column('past_history', sa.TEXT(), nullable=True),
    sa.Column('physical_exam', sa.TEXT(), nullable=True),
    sa.Column('diagnosis', sa.TEXT(), nullable=True),
    sa.Column('consultation_fee', sa.FLOAT(), nullable=True),
    sa.Column('total_amount', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('doctor_advice', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_timestamp'), ['timestamp'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('visit_id', sa.INTEGER(), nullable=True),
    sa.Column('nurse_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('receipt_printed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['nurse_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_table('diagnosis_dict',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('pinyin', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_dict', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_dict_pinyin'), ['pinyin'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_dict_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_dict_code'), ['code'], unique=False)

    op.create_table('patient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('grade', sa.VARCHAR(length=50), nullable=True),
    sa.Column('college', sa.VARCHAR(length=100), nullable=True),
    sa.Column('major', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_student_id'), ['student_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_patient_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('real_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=1)

    op.create_table('drug',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('specification', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=10), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drug', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drug_name'), ['name'], unique=False)

    # ### end Alembic commands ###
