"""add type to drug model

Revision ID: 30cd7660fff6
Revises: 8b91d87914f1
Create Date: 2026-03-19 10:49:07.096172

"""
from alembic import op
import sqlalchemy as sa

from backend.migrations.migration_helpers import (
    add_missing_columns,
    refuse_unsafe_downgrade,
)


# revision identifiers, used by Alembic.
revision = '30cd7660fff6'
down_revision = '8b91d87914f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    add_missing_columns(
        'drug',
        [sa.Column('type', sa.Integer(), nullable=True)],
    )

    # ### end Alembic commands ###


def downgrade():
    refuse_unsafe_downgrade(revision)
