"""add type to drug model

Revision ID: 30cd7660fff6
Revises: 8b91d87914f1
Create Date: 2026-03-19 10:49:07.096172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cd7660fff6'
down_revision = '8b91d87914f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
