"""Add doctor_advice to Visit

Revision ID: 34cd876ebf0a
Revises: c81ce2d3cc82
Create Date: 2026-03-18 16:21:56.566953

"""
from alembic import op
import sqlalchemy as sa

from backend.migrations.migration_helpers import (
    add_missing_columns,
    refuse_unsafe_downgrade,
)


# revision identifiers, used by Alembic.
revision = '34cd876ebf0a'
down_revision = 'c81ce2d3cc82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    add_missing_columns(
        'visit',
        [sa.Column('doctor_advice', sa.Text(), nullable=True)],
    )

    # ### end Alembic commands ###


def downgrade():
    refuse_unsafe_downgrade(revision)
