"""Add doctor_advice to Visit

Revision ID: 34cd876ebf0a
Revises: c81ce2d3cc82
Create Date: 2026-03-18 16:21:56.566953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34cd876ebf0a'
down_revision = 'c81ce2d3cc82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_advice', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_column('doctor_advice')

    # ### end Alembic commands ###
