"""Re-init

Revision ID: 3b3064ff1978
Revises: 
Create Date: 2026-03-18 14:28:42.494789

"""
from alembic import op
import sqlalchemy as sa

from backend.migrations.migration_helpers import (
    column_names,
    ensure_foreign_key,
    ensure_index,
    ensure_unique,
    inspector,
    refuse_unsafe_downgrade,
    require_table_shape,
    table_exists,
)


# revision identifiers, used by Alembic.
revision = '3b3064ff1978'
down_revision = None
branch_labels = None
depends_on = None


CORE_TABLE_SHAPES = {
    'drug': {'id', 'name', 'specification', 'unit', 'price', 'stock', 'status'},
    'patient': {
        'id', 'student_id', 'name', 'gender', 'class_name', 'phone', 'created_at',
    },
    'user': {'id', 'username', 'password_hash', 'real_name', 'role'},
    'visit': {
        'id', 'patient_id', 'doctor_id', 'timestamp', 'chief_complaint',
        'present_illness', 'past_history', 'physical_exam', 'diagnosis',
        'consultation_fee', 'total_amount', 'status',
    },
    'payment': {
        'id', 'visit_id', 'nurse_id', 'amount', 'payment_date',
        'payment_method', 'receipt_printed',
    },
    'prescription_item': {
        'id', 'visit_id', 'drug_id', 'usage', 'dosage', 'frequency', 'days',
        'quantity', 'price_at_visit', 'amount',
    },
}


def _preflight_existing_schema():
    existing = set(inspector().get_table_names()) - {'alembic_version'}
    present_core = set(CORE_TABLE_SHAPES) & existing
    if present_core and present_core != set(CORE_TABLE_SHAPES):
        unexpected_tables = existing - present_core
        if unexpected_tables:
            names = ', '.join(sorted(unexpected_tables))
            raise RuntimeError(
                'Refusing to resume a partial unversioned schema with '
                'unexpected tables: ' + names
            )

        bind = op.get_bind()
        preparer = bind.dialect.identifier_preparer
        nonempty_tables = []
        for table_name in sorted(present_core):
            required_columns = CORE_TABLE_SHAPES[table_name]
            require_table_shape(table_name, required_columns)
            actual_columns = column_names(table_name)
            if actual_columns != required_columns:
                extras = ', '.join(sorted(actual_columns - required_columns))
                raise RuntimeError(
                    f'Refusing to replace partial table {table_name!r}; '
                    f'unexpected columns: {extras}'
                )
            quoted_table = preparer.quote(table_name)
            if bind.execute(
                sa.text(f'SELECT 1 FROM {quoted_table} LIMIT 1')
            ).first():
                nonempty_tables.append(table_name)
        if nonempty_tables:
            names = ', '.join(nonempty_tables)
            raise RuntimeError(
                'Refusing to resume a partial unversioned schema with data in: '
                + names
            )

        for table_name in (
            'prescription_item', 'payment', 'visit', 'user', 'patient', 'drug',
        ):
            if table_name in present_core:
                op.drop_table(table_name)
        return

    for table_name, required_columns in CORE_TABLE_SHAPES.items():
        if table_name in present_core:
            require_table_shape(table_name, required_columns)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _preflight_existing_schema()
    if not table_exists('drug'):
        op.create_table('drug',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=True),
        sa.Column('specification', sa.String(length=50), nullable=True),
        sa.Column('unit', sa.String(length=10), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('stock', sa.Integer(), nullable=True),
        sa.Column('status', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    ensure_index('ix_drug_name', 'drug', ['name'])

    if not table_exists('patient'):
        op.create_table('patient',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.String(length=20), nullable=True),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('gender', sa.String(length=10), nullable=True),
        sa.Column('class_name', sa.String(length=100), nullable=True),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    ensure_index('ix_patient_name', 'patient', ['name'])
    ensure_index('ix_patient_student_id', 'patient', ['student_id'], unique=True)

    if not table_exists('user'):
        op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=True),
        sa.Column('password_hash', sa.String(length=128), nullable=True),
        sa.Column('real_name', sa.String(length=64), nullable=True),
        sa.Column('role', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    ensure_index('ix_user_username', 'user', ['username'], unique=True)

    if not table_exists('visit'):
        op.create_table('visit',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_id', sa.Integer(), nullable=True),
        sa.Column('doctor_id', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('chief_complaint', sa.Text(), nullable=True),
        sa.Column('present_illness', sa.Text(), nullable=True),
        sa.Column('past_history', sa.Text(), nullable=True),
        sa.Column('physical_exam', sa.Text(), nullable=True),
        sa.Column('diagnosis', sa.Text(), nullable=True),
        sa.Column('consultation_fee', sa.Float(), nullable=True),
        sa.Column('total_amount', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    ensure_index('ix_visit_timestamp', 'visit', ['timestamp'])

    if not table_exists('payment'):
        op.create_table('payment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('visit_id', sa.Integer(), nullable=True),
        sa.Column('nurse_id', sa.Integer(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('payment_date', sa.DateTime(), nullable=True),
        sa.Column('payment_method', sa.String(length=50), nullable=True),
        sa.Column('receipt_printed', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['nurse_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('visit_id')
        )
    if not table_exists('prescription_item'):
        op.create_table('prescription_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('visit_id', sa.Integer(), nullable=True),
        sa.Column('drug_id', sa.Integer(), nullable=True),
        sa.Column('usage', sa.String(length=100), nullable=True),
        sa.Column('dosage', sa.String(length=50), nullable=True),
        sa.Column('frequency', sa.String(length=50), nullable=True),
        sa.Column('days', sa.Integer(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('price_at_visit', sa.Float(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['drug_id'], ['drug.id'], ),
        sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    for table_name, required_columns in CORE_TABLE_SHAPES.items():
        require_table_shape(table_name, required_columns)

    ensure_foreign_key(
        'fk_visit_patient_id_patient',
        'visit',
        ['patient_id'],
        'patient',
        ['id'],
    )
    ensure_foreign_key(
        'fk_visit_doctor_id_user',
        'visit',
        ['doctor_id'],
        'user',
        ['id'],
    )
    ensure_unique('uq_payment_visit_id', 'payment', ['visit_id'])
    ensure_foreign_key(
        'fk_payment_visit_id_visit',
        'payment',
        ['visit_id'],
        'visit',
        ['id'],
    )
    ensure_foreign_key(
        'fk_payment_nurse_id_user',
        'payment',
        ['nurse_id'],
        'user',
        ['id'],
    )
    ensure_foreign_key(
        'fk_prescription_item_visit_id_visit',
        'prescription_item',
        ['visit_id'],
        'visit',
        ['id'],
    )
    ensure_foreign_key(
        'fk_prescription_item_drug_id_drug',
        'prescription_item',
        ['drug_id'],
        'drug',
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade():
    refuse_unsafe_downgrade(revision)
