"""add DiagnosisDict

Revision ID: 8b91d87914f1
Revises: 34cd876ebf0a
Create Date: 2026-03-19 10:00:12.745696

"""
from alembic import op
import sqlalchemy as sa

from backend.migrations.migration_helpers import (
    ensure_index,
    refuse_unsafe_downgrade,
    table_exists,
)


# revision identifiers, used by Alembic.
revision = '8b91d87914f1'
down_revision = '34cd876ebf0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('diagnosis_dict'):
        op.create_table('diagnosis_dict',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(length=50), nullable=True),
        sa.Column('name', sa.String(length=200), nullable=True),
        sa.Column('pinyin', sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    ensure_index('ix_diagnosis_dict_code', 'diagnosis_dict', ['code'])
    ensure_index('ix_diagnosis_dict_name', 'diagnosis_dict', ['name'])
    ensure_index('ix_diagnosis_dict_pinyin', 'diagnosis_dict', ['pinyin'])

    # ### end Alembic commands ###


def downgrade():
    refuse_unsafe_downgrade(revision)
