"""add DiagnosisDict

Revision ID: 8b91d87914f1
Revises: 34cd876ebf0a
Create Date: 2026-03-19 10:00:12.745696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b91d87914f1'
down_revision = '34cd876ebf0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('pinyin', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_dict', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_dict_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_dict_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnosis_dict_pinyin'), ['pinyin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosis_dict', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_dict_pinyin'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_dict_name'))
        batch_op.drop_index(batch_op.f('ix_diagnosis_dict_code'))

    op.drop_table('diagnosis_dict')
    # ### end Alembic commands ###
