"""add grade college major to patient

Revision ID: bbf28ffdb4c0
Revises: 30cd7660fff6
Create Date: 2026-03-23 14:08:25.283257

"""
from alembic import op
import sqlalchemy as sa

from backend.migrations.migration_helpers import (
    add_missing_columns,
    refuse_unsafe_downgrade,
)


# revision identifiers, used by Alembic.
revision = 'bbf28ffdb4c0'
down_revision = '30cd7660fff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    add_missing_columns(
        'patient',
        [
            sa.Column('grade', sa.String(length=50), nullable=True),
            sa.Column('college', sa.String(length=100), nullable=True),
            sa.Column('major', sa.String(length=100), nullable=True),
        ],
    )

    # ### end Alembic commands ###


def downgrade():
    refuse_unsafe_downgrade(revision)
