"""add grade college major to patient

Revision ID: bbf28ffdb4c0
Revises: 30cd7660fff6
Create Date: 2026-03-23 14:08:25.283257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf28ffdb4c0'
down_revision = '30cd7660fff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('college', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('major', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('major')
        batch_op.drop_column('college')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
