"""Add timing to PrescriptionItem

Revision ID: c81ce2d3cc82
Revises: 3b3064ff1978
Create Date: 2026-03-18 16:12:21.763211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81ce2d3cc82'
down_revision = '3b3064ff1978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timing', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_item', schema=None) as batch_op:
        batch_op.drop_column('timing')

    # ### end Alembic commands ###
