"""Add timing to PrescriptionItem

Revision ID: c81ce2d3cc82
Revises: 3b3064ff1978
Create Date: 2026-03-18 16:12:21.763211

"""
from alembic import op
import sqlalchemy as sa

from backend.migrations.migration_helpers import (
    add_missing_columns,
    refuse_unsafe_downgrade,
)


# revision identifiers, used by Alembic.
revision = 'c81ce2d3cc82'
down_revision = '3b3064ff1978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    add_missing_columns(
        'prescription_item',
        [sa.Column('timing', sa.String(length=50), nullable=True)],
    )

    # ### end Alembic commands ###


def downgrade():
    refuse_unsafe_downgrade(revision)
